### ISSUE TITLE
AOI Upload/Download: Cancel and clear tasks user notifications

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-h#26]
Does the "Clear Tasks" button cancel all the tasks? If yes, then please give a warning message so that the use can confirm their intention. Also, move the clear tasks button next to the cancel task button and rename it to cancel all tasks.

Similarly, if the cancel task process is irreversible, then the user should be warned after clicking on the cancel task button. 

What happens when clicking on the "Cancel" button when there are still processes in the queue? Does it automatically clear tasks? If yes, then please prompt a warning message.

**Comment by lbross** [comment]
The "Clear Tasks" button just clears the grid. I can add a warning that explains this and gives the opportunity to abort. Cancelling all tasks isn't a good option to add because they may be at different stages and some are not cancellable. You have to have a task selected in the tasks grid to click the "Cancel task" button.

Cancel task process is irreversible. Will add warning for user.

"Cancel" button does nothing to processes in the queue. This is asynchronous processing. It will clear all the grid displays on the form because when you open the form again, it is new.

**Comment by jdduh** [comment]
Ok! If the task list is cleared (by the Clear Tasks or by the Cancel button), how can I show/manage the Tasks in process? Is the information of the queue stored somewhere that can be retrieved later?

**Comment by lbross** [comment]
There is currently no way to show/manage the tasks in process if you clear the tasks grid or cancel the button (close the form). If we need this functionality, the best way to do it would be to have a service that takes the user id as input and returns a list of tasks that are currently in process. This would capture downloads that have been requested and are being compiled. Also uploads that have completed sending and are being added to the database. 

Alternatively, I could store a local file of what was on the grid but chances are that the data would be obsolete by the time the user reloaded it. 

Note that when an upload successfully completes, it will appear on the list of AOI's on the top of the form if you click the List button. Also you'll find your downloads locally on your computer.

**Comment by jkeifer** [comment]
This is exactly why the uploads and downloads endpoints are now filtered by user for all users. To get a list of a user's uploads, just GET /api/rest/uploads. Downloads are GET at /api/rest/downloads.

**Comment by jdduh** [comment]
The ideal behavior is to list just the tasks scheduled in the "current" session. In the current upload/download GUI design, the "Clear Tasks" or "Cancel" button, when clicked, signals the end of current session. I prefer that a "current" session ends when all tasks in process are completed. Here are some minor changes on the GUI:

1. Enable "Clear Tasks" only after all tasks are completed. Alternatively, only allow completed tasks to be removed from the list when "Clear Tasks" button is clicked. In this case, the button caption should be changed to "Remove completed tasks from list."
2. The "Cancel" button terminates all unfinished tasks. Users need to be notified if there are unfinished tasks in process.

Another approach is to maintain a list of "current tasks." When the upload/download dialog window is activated, the tool will retrieve the status of these tasks and re-populate the tasks in process list. This approach enables users to put the upload/download on the background and perform other GIS analyses. However, users might accidentally terminate ArcMap and cause the termination of some tasks.

**Comment by lbross** [comment]
@jkeifer Do the /api/rest/uploads and /api/rest/downloads return a list of currently processing tasks. That is, tasks that have a status other than SUCCESS or ABORTED? If so, querying these endpoints and building the task list is the best way to go. Since the tasks only take a few minutes, the chances of a user having tasks still running when the re-open the application is unlikely.

I agree with only clearing tasks from the task list with SUCCESS, FAILED, or ABORTED status and will change the button caption.

I disagree with terminating the tasks when "Cancel" is clicked. There are several points in processing when a task cannot be gracefully cancelled. Also, you can't always capture when the user closes the form in other ways so they could close the form without ending server tasks.

**Comment by jdduh** [comment]
If ArcMap is terminated before a task is completed, what status will the server assign to the task? We need to put a big warning message on the dialog windows saying that "all unfinished tasks will be aborted if ArcMap is closed."

Another less ideal approach is to create a "Show Recent Tasks" button that displays the tasks added to the queue within a time interval (e.g., last hour, today, this week, etc) specified by the user.

**Comment by jkeifer** [comment]
@lbross Currently those endpoints return all tasks regardless of status, unless you filter them explicitly. Uploads currently return their status as an integer, though I have been meaning to change that so they return their status as a string. For the time being, and your reference:

- 1: uploading file in progress
- 2: uploading file completed (task could be PENDING, STARTED, FAILED, or SUCCESS)
- 3: upload failed (this is a peculiar one)
- 4: upload and/or task aborted (either no task is listed or task could be PENDING, ABORTED*, FAILED, or SUCCESS)

I was thinking of reworking this a bit, so that the upload can have more states that will reflect the task state. And as you can see, there is a bit of ambiguity as to what you might get in each case.

But right now, if you GET /api/rest/uploads/?status=1, you'll get all upload records that have not been marked as having the upload portion complete (some portion of the file is still missing or the final POST request has not been made). GET /api/rest/uploads/?status=2 for all uploads that could have a task pending, started, failed, or with a non-aborted success. GET /api/rest/uploads/?status=3 will show you all uploads that have expired before they were completed; perhaps there are other reasons for this state which I am not remembering at the moment. GET /api/rest/uploads/?status=4 for all aborted tasks.

If this all sounds weird, it's because this upload model is a subclass of a generic upload model from a django python module I made called drf-chunked-upload, which I adapted from another module made to provide chunked upload capability for django forms. The upload class from ebagis has a lot strapped on to the base upload class, which has made the simple status field a bit precarious.

Downloads are completely different, as they do not inherit from a generic base class. They do not have their own status at all, but rather will always have a task object related to them (uploads don't get a task until they are marked as complete, at which point processing can begin). Thus, to filter downloads, you'd have to filter by the task status. And now that I'm writing this, I am thinking that can't be done unless I configure that filter explicitly, given that the filter would have to span a relation (the task is a separate model that is related back to the parent download object).

@jdduh ArcMap can close all it wants. It won't affect the server. If uploading a file is in progress, depending on how the file is being uploaded, it could easily be resumed later. If this is of particular concern, I imagine I could add some convenience methods to the upload class to return the current length of the file or last successful chunk and chunk size, or something like that, to help facilitate resuming an interrupted upload.

If an upload has been completed, then the server is completely autonomous. The desktop client has absolutely nothing to do to make the server happy. All the client's role is at that point is to communicate to the user the upload task's status until it complete and the AOI is fully added.

Downloads are similar but even less dependent on the client. The client is simply there to trigger the initial request to build the download, which the server does on it's own. The client then intermittently polls the server until the download is ready, at which point the client is served the file. But the server doesn't care if the client goes away completely and never returns--it's going to build the download and have it available, at this point for eternity (or until cleaned up manually; it is on the list to have an automated method to purge old downloads, and uploads too).

All this said, I thought the plan was to allow the server to manage all of this user history so that the desktop client can be pretty much dumb in that regard. Why try to maintain state that is already stored on the server and is easily accessible?

---
*Let me interject a note here about the ABORTED status. ABORTED is a transient state that is a flag to the task to tell it that it has been aborted. To properly handle that case, the task has to raise an AbortedError exception to force any database transactions to rollback to their start state (undoing any DB modifications). Once that is done I then catch that specific exception and return "Task aborted". As far as I could tell, there is no way for me to keep the ABORTED state; celery (the task framework) is either going to mark the task as FAILED (an exception was not handled and the task did not complete successfully), or SUCCESS (the task completed "successfully"). In the case of my abort handler, I figured it would be best to catch the exception and make it look like a successful execution rather than fail. That way if handling the abort goes sideways it will be obvious that it was not a successful abort.

**Comment by lbross** [comment]
Will not refresh tasks window when window is reloaded. Will warn when window closed if there are pending downloads that cannot be retrieved later because link is broken.

**Comment by lbross** [comment]
Discussed issue on 4/19/2016. Summary of changes related to the task list and associated buttons:

1. Move clear tasks button next to cancel task button; Rename to "Remove completed tasks from list"
2. Remove completed tasks from list button only removes completed, aborted, and failed tasks
3. Warn the user when "cancel task" button is pressed that the action is irreversible
4. Closing the form via cancel button, x in right-hand corner, or closing ArcMap removes visibility to any tasks running on the server. Warn user if they have tasks processing on the server. Try to catch all 3 of these events.
5. Decided NOT to list recently compiled downloads when user reconnects to server in new session for now. Documented in issue #29 if we want to reconsider later.

**Comment by lbross** [comment]
Coding for this issue is complete. The AOI download menu is modal so you can't close ArcMap without closing the menu first.
