### ISSUE TITLE
AOI Upload/Download: GUI modification: make tasks in process list resizable

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-h#27]
1. move the download and upload controls to the middle of the form (see image). Rename Download button caption to "Add download to task," rename Upload button to "Add upload to task."

![image](https://cloud.githubusercontent.com/assets/11510708/14448153/06d4d880-001b-11e6-9cb7-837e775c85dd.png)
1. make the tasks in process list resizable. When there are error messages returned to the tool, there is not enough space to view the complete message. I had to select the message and copy/paste to another editor to view the complete message. The scroll bar cannot perform scrolls inside a row when the row height exceeds the list height.
2. The upload comment field should be reset/cleared when an upload is added to the task.
3. Rename "View task log" to "View local AOI task log"
4. It's not clear what the function of the update status button is. It seems the task list can update itself in some situations, but not in some other situations. Please clarify.

**Comment by lbross** [comment]
See my comments:

1. "Add download to task" is not correct grammar. Could be either "Add download to tasks" or "Add download task". I like the second better because it's more concise. Will reorganize form. Also need to remove Upload Zip button. This was there for testing.

2. I ran into the issue myself with the error messages and could not find a way to view the complete message. This is a limitation of the GridBox control. May try adding a vertical scrollbar. Don't remember if I tried that or not.

3 and 4. Will do

5. This is confusing because .NET doesn't handle asynchronous processing well. As the state changes on the client side, I update the grid. For example: zipping an upload before sending it. But once it starts uploading, I have no way to check/update the status without sending repeated http:// requests. 

For downloads I have to send repeated http:// requests to know when the file is ready to download. I have a single timer that runs at 10 second intervals to check. Once the download starts, again, I have control on the client side so I can update the status. If this is confusing, I can not update the status but can cache the status in the form and only update it when the user clicks the update status button. The function of the update status button is to send an http:// request for each upload task in the list to check the status from the server.

Note that the UI does lock up during long running tasks like zipping up an AOI. The only way around this is to implement threading which I'm uncomfortable doing at this time. If not done exactly right, it can cause memory leaks and I don't want to go there.

**Comment by jdduh** [comment]
1. I thought about other captions. The main goal is to let users know that the download/upload is managed/monitored by a "queue." Add download/upload task sounds good to me.

2. You did add a vertical scroll bar, but it scrolls to the next row, not to the obscured portion of the row. Maybe resizing the list window can resolve the problem.

3.
4.
5. how about renaming the button caption to "Show completed tasks"?

6. I suppose the "Upload Zip" button allows users to select a zipped AOI and add the upload to the task list. Does the tool verify that the zip file contains a valid AOI? Please move the button to the space below the "Add upload task" button and change the caption to "Upload Zipped AOI."

Can you prompt a messagebox saying "Please wait... BAGIS is busy." or something like this when the UI is about to lock up? Hide the messagebox when UI becomes responsive (e.g., after the zip file is created). I know the status field shows similar message, but I think we need more notifications to let users know what is going on.

**Comment by lbross** [comment]
1. Will do
2. Not sure what you are suggesting here. I have experienced the problem. Do you want me to make the "tasks in process" grid taller all the time? Or try to make it taller if there is an error?
3.
4.
5. "Show completed tasks" isn't an accurate caption for the "update status" button because it updates the status on all upload tasks whether or not they are complete. "Update upload task status" may technically be more accurate but I don't know that it resolves confusion.
6. I used the "Upload zip" button during development before the code was written to create the .zip file. It wasn't intended for end users so doesn't have any checks like whether the AOI is valid or if it already exists. It's my preference to just remove this button. But, if you think it is something the users would like to have, I can open another issue to add this as an enhancement. To check to make sure it is a valid AOI, you'd have to unzip it, check, and then delete the output before trying to upload.
7. I'm not sure if a ProgressBar can help with the UI locking or not. I will run some tests and see what is possible. I opened issue #28 separately because this will take some additional time/research.

**Comment by jdduh** [comment]
1.
2. I suggest making the list window resizable.
3. How about just "Refresh task list"?
4. It's OK to remove/hide the Upload zip button.
5. Thanks

**Comment by lbross** [comment]
Discussed issue on 4/19/2016. Summary of changes related to the task list and associated buttons:

1. Move clear tasks button next to cancel task button; Rename to "Remove completed tasks from list"
2. Remove completed tasks from list button only removes completed, aborted, and failed tasks
3. Warn the user when "cancel task" button is pressed that the action is irreversible
4. Closing the form via cancel button, x in right-hand corner, or closing ArcMap removes visibility to any tasks running on the server. Warn user if they have tasks processing on the server. Try to catch all 3 of these events.
5. Decided NOT to list recently compiled downloads when user reconnects to server in new session for now. Documented in issue #29 if we want to reconsider later.

**Comment by lbross** [comment]
This note concerns the issue where long error messages cannot be read on the grid. Due to limitations of the DataGridView control, there is no way to make the cell big enough to display the whole message. Instead we now truncate the message in the grid at 100 characters and display the message in its entirety in a pop-up message box. Hopefully this is an acceptable work around. The 100 character limit is arbitrary but seemed to be a good length for showing that there is a message without maxing out the cell size.

**Comment by jdduh** [comment]
This works. Good solution.

**Comment by lbross** [comment]
Believe all of the items in this issue are done. See current screenshot to confirm:
![aoimenu](https://cloud.githubusercontent.com/assets/11527966/15087923/778970dc-13a2-11e6-8a63-4f24319f5b8a.png)

**Comment by jdduh** [comment]
Looks good. The View AOI history button should be associated with the list of AOIs on the server because we no longer keep track of the history of the downloaded local AOIs.

**Comment by lbross** [comment]
Correct. It is currently there as a placeholder but will be disabled until we have a working AOI history API from the server. @jdduh Do you think you have any time this week to take this screen for another test drive? If so, I'll post a new add-in to GitHub. It's always easier to fix things closer to when they were coded.
